version: '3.8'
services:
  backend:
    image: rakeshram909/ui-interface:v1
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /src/main/ui_interface/main.py'
    ports:
      - 5000:5000
    volumes:
      - .:/src/main
    depends_on:
      - db

  queue:
    image: rakeshram909/ui-interface-queue:v1
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /src/main/ui_interface/consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306