version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /src/main/ui_interface/main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/src/main

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /src/main/ui_interface/consumer.py'